COLUMNS:
  company: object
  typeName: object
  inches: object
  screenresolution: object
  cpu: object
  ram: object
  memory: object
  gpu: object
  opsys: object
  weight: object
  price: float64

TARGET_COLUMN:
  name: price